site_name: cookiecutter-golang-project Documentation
theme: 'material'
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - smarty
  - wikilinks
  - codehilite:
      linenums: True
extra:
  palette:
    primary: '#087da1'
    accent: '#00a889'
  font:
    text: 'Source Sans Pro'

repo_name: 'hadenlabs/cookiecutter-golang-project'
repo_url: 'https://github.com/hadenlabs/cookiecutter-golang-project'
copyright: 'Copyright Â© 2021 <a href="https://hadenlabs.com">hadenlabs</a>'

google_analytics:
  - ''
  - 'auto'
